### ISSUE TITLE
Downloading entire game into install folder

### ISSUE THREAD

**Issue by Sikksens** [CptBlacksheep/Launch-of-Exile#6]
Hey there,

When launching PoE it is downloading the game from scratch into the install folder of the app, I have pointed it to my standalone client.exe but still persists in trying to redownload the game.

**Comment by CptBlacksheep** [comment]
That shouldn't be possible, it's not capable of that. Are you sure you've chosen the right exe? I don't use the standalone client myself but there's probably some sort of repairexe, or it's just an update

**Comment by Sikksens** [comment]
Yea it's really weird, my game is fully up to date but it doesn't seem to recognize the game being in another folder and wants it in it's own folder.

![image](https://user-images.githubusercontent.com/15923337/169536433-5059663f-2931-4109-991e-94eac231a30a.png)

**Comment by CptBlacksheep** [comment]
That's weird... i will investigate it the upcomming days. Maybe i can come up with a solution.
