### ISSUE TITLE
Failed to launch JVM & Child process exited with code 1

### ISSUE THREAD

**Issue by xuvvy** [CptBlacksheep/Launch-of-Exile#7]
![image](https://user-images.githubusercontent.com/21984783/170057720-1375fe13-a5bb-4f05-9246-93e2de3a4f23.png)

![image](https://user-images.githubusercontent.com/21984783/170057776-715fa8a9-5915-483f-828a-ea983c446509.png)

This happens whenever the tool is launched, be it with admin rights or not. I am on Windows 11 and I cannot use the tool at all.

**Comment by CptBlacksheep** [comment]
Maybe the installation was corrupted in some way, have you tried to reinstall it? The current versions installer is working for me and friends, so it should theoretically be packaged correctly.
