### ISSUE TITLE
Awakened PoE Trade spams errors when launched through Launch of Exile

### ISSUE THREAD

**Issue by JaniHugsPlease** [CptBlacksheep/Launch-of-Exile#8]
When I try to launched Awakened PoE Trade via Launch of Exile I get spammed with errors. This does not happen if I launch it separately.  Both Launch of Exile and Awakened PoE Trade are up to date. I have also set to run as admin but it hasn't made a difference.

The error:

![Capture](https://user-images.githubusercontent.com/110821295/183395825-18f5b572-d491-44dc-bf20-26a2b83cc0bf.PNG)

**Comment by CptBlacksheep** [comment]
That's an error message from awakened poe trade not LoE, you should probably tell them about it. I haven't played since 2 months, but back then awakened poe trade worked perfectly fine with LoE for me and friends(maybe try to reinstall it).

**Comment by JaniHugsPlease** [comment]
Thanks for the response. I have tried reinstalling it multiple times and it only throws the error when launched via Launch of Exile which is weird.

**Comment by CptBlacksheep** [comment]
I tried it myself now and even with awakened updated to the newest version it's still working as intended. So unfortunately it seems like there's nothing i can do to help you, the problem seems to be somewhere else.

**Comment by JaniHugsPlease** [comment]
https://github.com/SnosMe/awakened-poe-trade/issues/690#issuecomment-1208211757

This is the response from the Awakened PoE Trade guys.

**Comment by CptBlacksheep** [comment]
mhh.. okay, i will look into it the upcomming days and try to solve it. But i can't promise anything.

**Comment by JaniHugsPlease** [comment]
Thank you for having a look.

**Comment by CptBlacksheep** [comment]
Ok i uploaded a new release that should theoretically fix your issue. Please tell me if it's solved now (as i couldn't reproduce and therefore couldn't test it).

**Comment by JaniHugsPlease** [comment]
Works perfectly :) Thank you for fixing.
